server:
  port: 8001 #Service port number
spring:
  application:
    name: microServiceCloudProviderDept  #The name of the microservice, the name of the microservice exposed to the outside world, is very important
  ################################################## JDBC config  ##########################################
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/luxbp_demo_jdbc       #database url
    driver-class-name: com.mysql.jdbc.Driver                  #database driver
############################### do not check spring.config.import=configserver:
#  cloud:
#    config:
#      enabled: false
###################################### MyBatis config ######################################
mybatis:
  # Specify the location of mapper.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  #The location of the scanned entity class, specify the package of the scanned entity class here, and the full path name of the entity class can not be written in mapper.xml
  type-aliases-package: com.luxbp.entity
  configuration:
    #The camel case is enabled by default, you don’t need to set this property
    map-underscore-to-camel-case: true
########################################### Spring cloud custom service name and ip address###############################################
eureka:
  client: #Register the client into the eureka service list
    service-url:
      # defaultZone: http://localhost:7001/eureka  #This address is the registration address exposed by the 7001 registration center in application.yml (stand-alone version)
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/  #Register the service with the Eureka Server cluster
  instance:
    instance-id: spring-cloud-provider-8001 #Custom service name information
    prefer-ip-address: true  #Display the ip address of the access path
########################################## Spring cloud uses Spring Boot actuator to monitor and improve information###################################
# Spring Boot 2.50 shields most of the nodes for actuator monitoring, and only exposes the heath node. The configuration (*) in this section is to enable all nodes
management:
  endpoints:
    web:
      exposure:
        include: "*"   # * is a keyword in the yaml file, so quotation marks are required
info:
  app.name: micro-service-cloud-provider-dept
  company.name: luxbp.com
  build.aetifactId: @project.artifactId@
  build.version: @project.version@