spring:
  application:
    name: microServiceCloudProviderDeptHystrix
server:
  port: 8004
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: spring-cloud-provider-8004
    prefer-ip-address: true
# Spring Boot 2.50 shields most of the nodes for actuator monitoring, and only exposes the heath node. The configuration (*) in this section is to enable all nodes
management:
  endpoints:
    web:
      exposure:
        include: "*"   # * is a keyword in the yaml file, so quotation marks are required
info:
  app.name: micro-service-cloud-provider-dept-hystrix
  company.name: luxbp.com
  build.aetifactId: @project.artifactId@
  build.version: @project.version@