server:
  port: 7001  #The port number of the Module
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false #false means do not register itself with the registry
    fetch-registry: false #Set to False because that my end is the registration center, and my responsibility is to maintain the service instance, and there is no need to retrieve the service
    service-url:
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #Stand-alone service registration center
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ #cluster version. Register the current Eureka Server to 7002 and 7003 to form a group of Eureka Server clusters registered with each other