server:
  port: 7001  #The port number of the Module / 该 Module 的端口号
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false #false means do not register itself with the registry. / false表示不向注册中心注册自己。
    fetch-registry: false #False means that my end is the registration center, and my responsibility is to maintain the service instance, and there is no need to retrieve the service / false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #Stand-alone service registration center / 单机版服务注册中心
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ #集群版 将当前的 Eureka Server 注册到 7003 和 7003 上，形成一组互相注册的 Eureka Server 集群 / cluster version Register the current Eureka Server to 7003 and 7003 to form a group of Eureka Server clusters registered with each other