server:
  port: 9527
spring:
  application:
    name: microServiceCloudGateway
  cloud:
    gateway: #route config of gateway
      discovery:
        locator:
          enabled: true # true by default: routing is performed using the microservice name with LB protocol instead of specific url
      routes:
#        - id: provider_dept_list_routh   #route id,no special naming principles，but it should be unique，Strongly recommend identical with service name
#          uri: lb://MICROSERVICECLOUDPROVIDERDEPT #dynamic route，using lb protocal. lb://${servicename}. Calling relevant services.
#          predicates:
#            # will triggered this rule only if all the rules below are matched.
#            - Path=/f/dept/list/**
#            - Method=GET # access only if request method is GET
#        - id: provider_dept_get_routh
#          uri: lb://MICROSERVICECLOUDPROVIDERDEPT
#          predicates:
#            - Path=/f/get/**
#          filters:
#            - PrefixPath=/dept #intercept request and add a prefix to request url.
        - id: consumer_dept_feign_list
          uri: lb://MICROSERVICECLOUDCONSUMERDEPTFEIGN
          predicates:
            - Path=/f/dept/list
            - Method=GET
        - id: consumer_dept_feign_get
          uri: lb://MICROSERVICECLOUDCONSUMERDEPTFEIGN
          predicates:
            - Path=/f/dept/get/**
            - Method=GET
        - id: consumer_dept_feign_add_student
          uri: lb://MICROSERVICECLOUDCONSUMERDEPTFEIGN
          predicates:
            - Path=/f/student/add
            - Method=POST
eureka:
  instance:
    instance-id: micro-service-cloud-gateway-9527
    hostname: micro-service-cloud-gateway
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/