server:
  port: 80
spring:
  application:
    name: microServiceCloudConsumerDeptFeign
eureka:
  client:
    register-with-eureka: true # get registered
    fetch-registry: true  # fetch service
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: consumer-feign-80
ribbon:
  ReadTimeout: 6000 #The time taken to establish a connection, applicable to the time taken by both ends of the connection when the network condition is normal
  ConnectionTimeout: 6000 #After the connection is established, the time when the server reads the available resources
logging:
  level:
    #What level does the feign log monitor the interface at?
    com.luxbp.service.DeptFeignService: debug
feign:
  hystrix:
    enabled: true #Open the client hystrix
######################Configure request timeout##########################
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 7000
    ####################Configure the specific method timeout as 3 seconds########################
    DeptHystrixService#deptInfo_Timeout(Integer):
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
