server:
  port: 8082
spring:
  application:
    name: scheduledJobsApplication
eureka:
  client: #Register the client into the eureka service list
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/  #Register the service with the Eureka Server cluster
  instance:
    instance-id: scheduled-jobs-application-8082
    prefer-ip-address: true