server:
  port: 8081
spring:
  application:
    name: commandLineApplication

eureka:
  client: #Register the client into the eureka service list
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/  #Register the service with the Eureka Server cluster
  instance:
    instance-id: command-line-application-8081
    prefer-ip-address: true